package com.example.jibi.util

object PreferenceKeys {
    // Shared Preference Files:
    const val APP_MAIN_PREFERENCES:String="APP_MAIN_PREFERENCES"
    // Shared Preference Keys
    const val PROMOTE_FAB_TRANSACTION_FRAGMENT="PREFERENCES_PROMOTE_FAB_TRANSACTION_FRAGMENT"
    const val PROMOTE_ADD_TRANSACTION="PREFERENCES_PROMOTE_ADD_TRANSACTION"
    const val PROMOTE_CATEGORY_LIST="PREFERENCES_PROMOTE_CATEGORY_LIST"
    const val PROMOTE_VIEW_CATEGORY_LIST="PREFERENCES_PROMOTE_VIEW_CATEGORY_LIST"
    const val PROMOTE_ADD_CATEGORY_NAME="PREFERENCES_PROMOTE_ADD_CATEGORY_NAME"
}